# Generated by Django 3.1.1 on 2020-09-22 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnb',
            name='checkin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='airbnb',
            name='house_photos',
            field=models.ImageField(default='', upload_to='post/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airbnb',
            name='house_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='airbnb',
            name='owner_mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
