# Generated by Django 3.1.1 on 2020-09-22 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_auto_20200922_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbnb',
            old_name='checkin_date',
            new_name='arrival_date',
        ),
        migrations.AddField(
            model_name='airbnb',
            name='departure_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
