# Generated by Django 3.1.1 on 2020-09-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0004_airbnb_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnb',
            name='ROOM_STATUES',
            field=models.CharField(choices=[('single', 'single'), ('double', 'double')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='airbnb',
            name='SMOKING_CHOICES',
            field=models.CharField(choices=[('smoke', 'smoke'), ('not smoke', 'not smoke')], default='smoke', max_length=20),
        ),
    ]
